@startuml  
class foo
foo --> bar             : обычный
foo --> bar1 #line:red;line.bold;text:red    : красный, жирный
foo --> bar2 #green;line.dashed;text:green    : зеленый, штрих
foo --> bar3 #blue;line.dotted;text:blue    : синий, пунктир

@enduml

