@startuml 
autonumber 1.1.1
Alice -> Bob: Authentication request
Bob --> Alice: Response

autonumber inc A
'now we have 2.1.1
Alice -> Bob: Another authentication request
Bob --> Alice: Response

autonumber inc B
'now we have 2.2.1
Alice -> Bob: Another authentication request
Bob --> Alice: Response

autonumber inc A
'now we have 3.1.1
Alice -> Bob: Another authentication request
Bob --> Alice: Response

autonumber inc B
'now we have 3.2.1
Bob --> Alice: Response

@enduml
